/**
 * Created by v-yaf_000 on 2016/5/30.
 */
// 数据同步配置

exports.hotCastConfig=[
    {
    name:"美女",
    categoryId:"Bkz3X4KX",
    hotCastId:"56b07c548f95d",
    },
    {
    name:"运动",
    categoryId:"r1n6mNYm",
    hotCastId:"56b07c549218a",
    },
    {
    name:"冒险",
    categoryId:"Bybg4NF7",
    hotCastId:"56b07c54950ef",
    },
    {
    name:"科技",
    categoryId:"SkbWEVFX",
    hotCastId:"56b07c5497837",
    },
    {
    name:"影视",
    categoryId:"rJaGNNK7",
    hotCastId:"56b07c5499a38",
    },

];

exports.vrWorldConfig=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"美女",
        vrWorldId:"13",
    },
    {
        name:"科技",
        categoryId:"Bkz3X4KX",
        vrname:"科幻",
        vrWorldId:"9",
    },
    {
        name:"恐怖",
        categoryId:"Bkz3X4KX",
        vrname:"恐怖",
        vrWorldId:"10",
    },
    {
        name:"影视",
        categoryId:"Bkz3X4KX",
        vrname:"喜剧",
        vrWorldId:"11",
    },
    {
        name:"娱乐",
        categoryId:"Bkz3X4KX",
        vrname:"热舞",
        vrWorldId:"12",
    },
    {
        name:"冒险",
        categoryId:"Bkz3X4KX",
        vrname:"动作",
        vrWorldId:"14",
    },
    {
        name:"娱乐",
        categoryId:"Bkz3X4KX",
        vrname:"娱乐",
        vrWorldId:"15",
    },
    {
        name:"娱乐",
        categoryId:"Bkz3X4KX",
        vrname:"汽车",
        vrWorldId:"16",
    },
    {
        name:"运动",
        categoryId:"Bkz3X4KX",
        vrname:"体育",
        vrWorldId:"17",
    },
    {
        name:"游戏",
        categoryId:"Bkz3X4KX",
        vrname:"游戏",
        vrWorldId:"18",
    },
    {
        name:"旅游",
        categoryId:"Bkz3X4KX",
        vrname:"旅游",
        vrWorldId:"21",
    },
    {
        name:"娱乐",
        categoryId:"Bkz3X4KX",
        vrname:"音乐",
        vrWorldId:"22",
    },

]

//{ id: '9', classify: '0', name: '科幻', icon: '', is_home: '2' },
//{ id: '10', classify: '0', name: '恐怖', icon: '', is_home: '2' },
//{ id: '11', classify: '0', name: '喜剧', icon: '', is_home: '2' },
//{ id: '12', classify: '0', name: '热舞', icon: '', is_home: '2' },
//{ id: '13', classify: '0', name: '美女', icon: '', is_home: '2' },
//{ id: '14', classify: '0', name: '动作', icon: '', is_home: '2' },
//{ id: '15', classify: '0', name: '娱乐', icon: '', is_home: '2' },
//{ id: '16', classify: '0', name: '汽车', icon: '', is_home: '2' },
//{ id: '17', classify: '0', name: '体育', icon: '', is_home: '2' },
//{ id: '18', classify: '0', name: '游戏', icon: '', is_home: '2' },
//{ id: '20',
//    classify: '0',
//    name: '旅游',
//    icon: 'http://oss.gevek.com/apk/20150825/shiwangelengxiaohua/shiwangelengxiaohua.png?auth_key=1465444102-0-0-56c311abb490749691adb64fe9bf27af',
//    is_home: '1' },
//{ id: '22',
//    classify: '0',
//    name: '音乐',
//    icon: 'http://oss.gevek.com/apk/20150901/ff3/ff3.png?auth_key=1465444102-0-0-2877dc09cd8351bb0f341cf6e6224b5f',
//    is_home: '1' } ] }

exports.vrSeeFileConfig=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        hotCastId:1,
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        hotCastId:2,
    },
    {
        name:"游戏",
        categoryId:"S1DaUSBE",
        hotCastId:3,
    },
    {
        name:"科技",
        categoryId:"SkbWEVFX",
        hotCastId:4,
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        hotCastId:5,
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        hotCastId:7,
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        hotCastId:8,
    }

];
exports.vrBaofengConfig=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"性感女团：翘臀大长腿来袭",
        hotCastId:210,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/210.js "
    },
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"深夜大妞趴",
        hotCastId:424,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/424.js "
    },
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"女友福利社（每周二性感来袭）",
        hotCastId:440,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/440.js"
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        vrname:"极限者联盟",
        hotCastId:430,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/430.js  "
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        vrname:"极限体验：玩的就是心跳",
        hotCastId:149,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/149.js"
    },
    {
        name:"科幻",
        categoryId:"SkbWEVFX",
        vrname:"科幻大片",
        hotCastId:343,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/343.js "
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        vrname:"悬疑惊悚：真实感官吓破胆",
        hotCastId:87,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/87.js "
    },
    {
        name:"游戏",
        categoryId:"S1DaUSBE",
        vrname:"游戏大作：精致画面颠覆体验",
        hotCastId:129,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/129.js"
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"海底世界：神秘梦幻叹为观止",
        hotCastId:284,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/284.js"
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"环球旅行：带你走遍地球美景",
        hotCastId:187,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/187.js"
    },
    {
        name:"影视",
        categoryId:"rJaGNNK7",
        vrname:"VR佳片有约（每周一震撼首发）",
        hotCastId:461,
        url:"http://img.static.mojing.cn/resource/newmarket/android/20151016/list/column/461.js"
    },


];
exports.utoVRConfig=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"美女",
        hotCastId:22,
        url:""
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        vrname:"极限运动",
        hotCastId:11,
        url:""
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        vrname:"惊悚",
        hotCastId:25,
        url:""
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"旅游",
        hotCastId:12,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"创意",
        hotCastId:13,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"偶像",
        hotCastId:10,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"音乐",
        hotCastId:9,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"综艺",
        hotCastId:24,
        url:""
    },

    {
        name:"其他",
        categoryId:"rklDecGSB",
        vrname:"虚拟现实",
        hotCastId:8,
        url:""
    },
    {
        name:"其他",
        categoryId:"rklDecGSB",
        vrname:"其他",
        hotCastId:6,
        url:""
    },
];
exports.vr720YunConfig=[
    {
    name:"其他",
    categoryId:"rklDecGSB",
    vrname:"其他",
    hotCastId:0,
    url:""
    },
];
exports.vrTimes=[
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"音乐天地",
        hotCastId:2,
        url:""
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"自然风景",
        hotCastId:3,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"虚拟空间",
        hotCastId:4,
        url:""
    },
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"舞动青春",
        hotCastId:5,
        url:""
    },
    {
        name:"游戏",
        categoryId:"S1DaUSBE",
        vrname:"炫酷游戏",
        hotCastId:6,
        url:""
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        vrname:"诡异过度",
        hotCastId:7,
        url:""
    },
    {
        name:"其他",
        categoryId:"rklDecGSB",
        vrname:"热门视频",
        hotCastId:1,
        url:""
    },
];
exports.vrSanMonConfig=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"美女热舞",
        hotCastId:0,
        classifyId:2,
        url:""
    },
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"美女",
        hotCastId:3,
        classifyId:3,
        url:""
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"风景",
        hotCastId:4,
        classifyId:3,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"音乐",
        hotCastId:2,
        classifyId:3,
        url:""
    },
    {
        name:"影视",
        categoryId:"rJaGNNK7",
        vrname:"体验",
        hotCastId:1,
        classifyId:3,
        url:""
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        vrname:"竞速",
        hotCastId:5,
        classifyId:3,
        url:""
    },
    {
        name:"科技",
        categoryId:"SkbWEVFX",
        vrname:"科幻",
        hotCastId:27,
        classifyId:4,
        url:""
    },
    {
        name:"影视",
        categoryId:"rJaGNNK7",
        vrname:"动作",
        hotCastId:28,
        classifyId:4,
        url:""
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        vrname:"恐怖",
        hotCastId:32,
        classifyId:4,
        url:""
    },

    ];
exports.vr800Config=[
    {
        name:"美女",
        categoryId:"Bkz3X4KX",
        vrname:"美女",
        hotCastId:10,
        url:""
    },
    {
        name:"影视",
        categoryId:"rJaGNNK7",
        vrname:"影视",
        hotCastId:9,
        url:""
    },
    {
        name:"冒险",
        categoryId:"Bybg4NF7",
        vrname:"极限",
        hotCastId:2,
        url:""
    },
    {
        name:"游戏",
        categoryId:"S1DaUSBE",
        vrname:"游戏",
        hotCastId:8,
        url:""
    },
    {
        name:"科技",
        categoryId:"SkbWEVFX",
        vrname:"科技",
        hotCastId:12,
        url:""
    },
    {
        name:"旅游",
        categoryId:"B1S0LSSV",
        vrname:"旅行",
        hotCastId:3,
        url:""
    },
    {
        name:"其他",
        categoryId:"rklDecGSB",
        vrname:"原创",
        hotCastId:11,
        url:""
    },
    {
        name:"恐怖",
        categoryId:"BJu8ISrE",
        vrname:"惊悚",
        hotCastId:4,
        url:""
    },
    {
        name:"娱乐",
        categoryId:"rkTKIrrN",
        vrname:"明星",
        hotCastId:6,
        url:""
    },
]